apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.app_name }}
  name: {{ .Values.app_name }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32323
  selector:
    app: {{ .Values.app_name }}
  type: NodePort
status:
  loadBalancer: {}